<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>area_area</name>
   <tag></tag>
   <elementGuidId>43d84b26-e99c-4d08-a689-67b702f758e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[title=&quot;&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@title = '']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>area</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>area</value>
      <webElementGuid>ad93a5bc-0de4-46d9-8ab7-babae85dee60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>log</name>
      <type>Main</type>
      <value>miw</value>
      <webElementGuid>9cfd2d8a-597d-4db6-8ce3-1b3418aed9a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>coords</name>
      <type>Main</type>
      <value>13,0,4,3.5,0,12,2.75,21,13,37,23.5,21,26,12,22,3.5</value>
      <webElementGuid>2f9ff674-721c-4efc-b7c3-0d20d0cbef1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shape</name>
      <type>Main</type>
      <value>poly</value>
      <webElementGuid>ffe129c4-c8f1-49bd-a5f7-7382ef9c851a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>56cc978f-dfce-4eb0-a77b-d2aa17470457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-18325964d6597b45b4c5eadaea8e08fc</value>
      <webElementGuid>6ccf0d21-0250-4f78-856b-2f0d5112db89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@title = '']</value>
      <webElementGuid>9dac80f4-780a-468c-acc9-59044d7d479e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@title = '']</value>
      <webElementGuid>3df2d713-c2d4-4a7d-a8be-411f5f71b1ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
