<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contoh_ 2.3361</name>
   <tag></tag>
   <elementGuidId>75ed1a29-4364-434a-8d6b-c8cdcd259f01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#create_latitude</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'create_latitude']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Contoh: 2.3361&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f271a265-9bfa-41de-9194-2c7477d5d3d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>35f60dbd-9a43-4695-b022-20d7eba19904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>latitude</value>
      <webElementGuid>2da49ce7-1732-4766-b2ee-198c5d8538d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>create_latitude</value>
      <webElementGuid>f976c924-b225-4321-a520-7dcd479d7d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: 2.3361</value>
      <webElementGuid>a16ff3a0-4e3d-4fdb-92d9-951f598c7cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full border border-gray-200 rounded-xl px-4 py-3.5 focus:ring-2 focus:ring-sidebar/10 focus:border-sidebar outline-none transition-all text-sm font-medium text-gray-700</value>
      <webElementGuid>a5dda3f8-d732-40ff-861f-369c6fc526dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e558e3335cf64e372defa2cd4cd46ea0</value>
      <webElementGuid>058aa894-64a0-4f6b-949d-a778637d687d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'create_latitude']</value>
      <webElementGuid>1fdd1b8f-1e8e-4d64-9e21-08b2297f769f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'create_latitude']</value>
      <webElementGuid>4566e49a-df77-449f-b956-05a6a128976f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'latitude' and @id = 'create_latitude' and @placeholder = 'Contoh: 2.3361']</value>
      <webElementGuid>2ecb7a03-736f-4242-8ea6-ea6cd66d194d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
