<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contoh_ 99.0494</name>
   <tag></tag>
   <elementGuidId>5db8edc3-e6a5-4aed-98b3-802a1a1330ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#create_longitude</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'create_longitude']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Contoh: 99.0494&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7d049bd-32b9-45a7-8e6b-dfe2afe56e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ccc57350-a8a0-47d0-a175-df91ba99b655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>longitude</value>
      <webElementGuid>926a5c20-d8c7-4fb0-adb2-0f7d9db17a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>create_longitude</value>
      <webElementGuid>641ff134-d04a-47f3-ade4-2e36dfaca127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: 99.0494</value>
      <webElementGuid>f3b4b91c-0614-4a8d-bd54-289f28f5726f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full border border-gray-200 rounded-xl px-4 py-3.5 focus:ring-2 focus:ring-sidebar/10 focus:border-sidebar outline-none transition-all text-sm font-medium text-gray-700</value>
      <webElementGuid>d8428625-7cc3-4592-9a5d-4e6ea94220e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-fad19d8bdcaed168e50fdbe97a7fdc23</value>
      <webElementGuid>2e329980-7d04-47c2-b244-23753ed4e403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'create_longitude']</value>
      <webElementGuid>696a7de2-6be6-4d9c-9421-f37a17811838</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'create_longitude']</value>
      <webElementGuid>7147381f-3d72-4961-8495-3a0ccf297cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'longitude' and @id = 'create_longitude' and @placeholder = 'Contoh: 99.0494']</value>
      <webElementGuid>5943996d-9956-4ee6-8b20-3d18f065262b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
