<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_monthlyChart</name>
   <tag></tag>
   <elementGuidId>4a6d3c3a-39cb-4f62-95cf-9ec2acba80c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#monthlyChart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'monthlyChart']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;JunJulAugSepOctNovDecJanFebMarAprMay&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>c099e53c-8c92-42cc-abae-b7b4814eaa05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>monthlyChart</value>
      <webElementGuid>38286d19-6dd7-4211-9aa8-f2fedec15f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>927</value>
      <webElementGuid>d0fae484-dd08-4394-9144-7664c6c5a818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>315</value>
      <webElementGuid>7da715f4-8779-4c93-9a1a-cd56637114d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JunJulAugSepOctNovDecJanFebMarAprMay</value>
      <webElementGuid>c3e9e6bf-712e-400b-a532-9662d8a35fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-18f9ae7337ab5c68a92936fd40752b42</value>
      <webElementGuid>766ffa78-42f0-4699-843d-a1d7688851c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'monthlyChart']</value>
      <webElementGuid>28d37b08-aacd-45d6-bcfa-47f8417e5cbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'monthlyChart']</value>
      <webElementGuid>dc58d683-d135-4973-a988-068014c648f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'monthlyChart' and (text() = 'JunJulAugSepOctNovDecJanFebMarAprMay' or . = 'JunJulAugSepOctNovDecJanFebMarAprMay')]</value>
      <webElementGuid>cefc9df5-cfbc-4225-9817-1d26fee938fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
