<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_21</name>
   <tag></tag>
   <elementGuidId>43a9dda4-3238-4e02-bb0d-5308d97d468e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.shadow-sm.flex-col:nth-child(1) p.font-bold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' shadow-sm ') and contains(concat(' ', normalize-space(@class), ' '), ' flex-col ') and (position() = 1)]//p[@class and contains(concat(' ', normalize-space(@class), ' '), ' font-bold ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;21&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d88cea3c-f6b8-49e0-96dd-360ef96a92e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-3xl font-bold text-gray-900</value>
      <webElementGuid>1d51de5d-b8cb-4d57-8030-9acfae14d7aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>58180248-e526-4566-9cf1-2d545365e715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-abb832c01856d3adde23dad4d0cb212f</value>
      <webElementGuid>dbc6d515-6594-43a9-a565-a78ae6752874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' shadow-sm ') and contains(concat(' ', normalize-space(@class), ' '), ' flex-col ') and (position() = 1)]//p[@class and contains(concat(' ', normalize-space(@class), ' '), ' font-bold ')]</value>
      <webElementGuid>1042ab99-2af6-4ee6-a069-a908dc87db6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' shadow-sm ') and contains(concat(' ', normalize-space(@class), ' '), ' flex-col ') and (position() = 1)]//p[@class and contains(concat(' ', normalize-space(@class), ' '), ' font-bold ')]</value>
      <webElementGuid>0fc51a05-ba23-48b0-972c-5b7700f5aa60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '21' or . = '21')]</value>
      <webElementGuid>953cb8f7-320b-4f0c-ac83-1e441182cdd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
