<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path_path</name>
   <tag></tag>
   <elementGuidId>2b1332e3-b079-470c-b569-014d081ead05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' text-white ') and contains(concat(' ', normalize-space(@class), ' '), ' transition-colors ')]//path[(@stroke-linejoin = 'round') and (@stroke-linecap = 'round')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.text-white.transition-colors path[stroke-linejoin=&quot;round&quot;][stroke-linecap=&quot;round&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>button >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>870d9244-d717-4c70-8f2e-a81e4fff3fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>bcdecb84-4498-4c52-9b89-a2d534a038fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>fb5d5c0a-95fa-450d-a776-c07cb43b3cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>9578ff9f-ce51-45cd-aa96-5da9d87f54f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M6 18L18 6M6 6l12 12</value>
      <webElementGuid>e0278346-4144-4d6d-afd0-8f0d758bea14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0dbb2f047f8d8c954811c24c34e18c00</value>
      <webElementGuid>46c6fe7f-771b-4518-994d-b16c88368fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' text-white ') and contains(concat(' ', normalize-space(@class), ' '), ' transition-colors ')]//path[(@stroke-linejoin = 'round') and (@stroke-linecap = 'round')]</value>
      <webElementGuid>dd5e308b-c3dd-40c5-a6ac-055e2e74b618</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' text-white ') and contains(concat(' ', normalize-space(@class), ' '), ' transition-colors ')]//path[(@stroke-linejoin = 'round') and (@stroke-linecap = 'round')]</value>
      <webElementGuid>674d0dfc-6fed-49e6-98e0-c8ef8e912c67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
