<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_fixed inset-0 transition-opacity bg-black_40</name>
   <tag></tag>
   <elementGuidId>10e88615-0e97-41ec-a3d9-92409477460c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.backdrop-blur-sm.ease-out</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' backdrop-blur-sm ') and contains(concat(' ', normalize-space(@class), ' '), ' ease-out ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(5) > div > .fixed</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b231aece-5786-4006-ae89-fb49aa706618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-show</name>
      <type>Main</type>
      <value>showEditModal</value>
      <webElementGuid>2ded0f64-77ce-46b4-b2ae-336a940a064e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-transition:enter</name>
      <type>Main</type>
      <value>ease-out duration-300</value>
      <webElementGuid>67364905-994e-42aa-92a0-cae87c4f4c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-transition:enter-start</name>
      <type>Main</type>
      <value>opacity-0</value>
      <webElementGuid>2fcc5d08-c88e-4253-8eba-8848d557290c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-transition:enter-end</name>
      <type>Main</type>
      <value>opacity-100</value>
      <webElementGuid>d75cafa2-1fcb-48cf-bfb5-ef3ebd1b1b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-transition:leave</name>
      <type>Main</type>
      <value>ease-in duration-200</value>
      <webElementGuid>ccecdbd2-62b2-422c-9528-3cef0d5aec2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-transition:leave-start</name>
      <type>Main</type>
      <value>opacity-100</value>
      <webElementGuid>6ca118c9-e816-478e-acac-f26a34883375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-transition:leave-end</name>
      <type>Main</type>
      <value>opacity-0</value>
      <webElementGuid>2a064df1-7db7-466e-9e2a-5725c74c648f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fixed inset-0 transition-opacity bg-black/40 backdrop-blur-sm opacity-0 ease-out duration-300</value>
      <webElementGuid>5e9c9343-9170-4101-99b7-b5c878bb192f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@click</name>
      <type>Main</type>
      <value>showEditModal = false</value>
      <webElementGuid>9e89cd98-12c2-43b5-acbe-4bb3cc86d46a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-999ec8bcd78306ed2133b6696b4dcea0</value>
      <webElementGuid>828017e6-adaf-4157-8213-390d2897f8e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' backdrop-blur-sm ') and contains(concat(' ', normalize-space(@class), ' '), ' ease-out ')]</value>
      <webElementGuid>7a1f91b8-6e73-44be-ac5a-0caf58725c7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' backdrop-blur-sm ') and contains(concat(' ', normalize-space(@class), ' '), ' ease-out ')]</value>
      <webElementGuid>4b4055fb-99bf-4997-820d-3d67530716d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
