<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_edit_latitude</name>
   <tag></tag>
   <elementGuidId>8354e9ad-00c8-48e3-8a73-938fcdf309ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit_latitude</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'edit_latitude']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#edit_latitude</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e312077-8b16-4e59-acd1-3e5deddeec04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a88c0b8e-c3c1-4ddc-949e-5883c8512575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>latitude</value>
      <webElementGuid>30343f11-20e8-492a-a10d-e040080ecd91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit_latitude</value>
      <webElementGuid>7d1d6c0b-756a-4e98-9cce-743c98a7ba27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-model</name>
      <type>Main</type>
      <value>editingDest.latitude</value>
      <webElementGuid>2c3bc174-2039-4fd9-94e3-fe176f0fbc77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full border border-gray-200 rounded-xl px-4 py-3.5 focus:ring-2 focus:ring-sidebar/10 focus:border-sidebar outline-none text-sm font-medium text-gray-700</value>
      <webElementGuid>118cfc7f-d997-470e-be88-2274d3882b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-9fea24020b783bb23151b991ed33a4e9</value>
      <webElementGuid>402f6baf-e803-4dc3-aeae-471edaf5290f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'edit_latitude']</value>
      <webElementGuid>60245aa3-af41-49f6-b0b4-0e08d5af9c84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'edit_latitude']</value>
      <webElementGuid>7f56c051-5078-44ed-bc7d-7830c86552dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'latitude' and @id = 'edit_latitude']</value>
      <webElementGuid>ba268643-ae8a-42cb-a584-fb0654b34b82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
