<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Klik untuk upload foto</name>
   <tag></tag>
   <elementGuidId>1dc6471a-b3db-47ac-b285-31a3b780c029</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#create_thumbnail</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'file' and @name = 'thumbnail' and @id = 'create_thumbnail']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'create_thumbnail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Klik untuk upload foto\n                                    PNG, JPG, WEBP (Maks. 5MB)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7290be69-e690-47b5-918b-155eb03aa96a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>faf5866a-c0c3-4940-9812-4c68a3402f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>thumbnail</value>
      <webElementGuid>db2c6d4e-a683-4f90-849d-f9b58aa132cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>create_thumbnail</value>
      <webElementGuid>042fe64d-9bf3-4fcc-b2d9-908917dde1c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute inset-0 opacity-0 cursor-pointer</value>
      <webElementGuid>d346f2c3-45b3-4dd5-8564-ab404f31e31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@change</name>
      <type>Main</type>
      <value>createFileName = $event.target.files[0] ? $event.target.files[0].name : ''</value>
      <webElementGuid>6e3013b6-079d-44bb-ad7e-cbff08741d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5ec595675adf6a01bcef6d6cf9fc2a6e</value>
      <webElementGuid>bbda4183-ca3a-4117-b1d7-b24fb7a3e384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'create_thumbnail']</value>
      <webElementGuid>0ce39079-5154-439f-8545-047f316e4400</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'create_thumbnail']</value>
      <webElementGuid>2068b8f5-1aec-4c13-8f22-7bdc8bbce836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'thumbnail' and @id = 'create_thumbnail']</value>
      <webElementGuid>6bd2b9a8-7947-4e56-b8c7-53b21f8b72c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
