<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_edit_longitude</name>
   <tag></tag>
   <elementGuidId>6aec6182-b409-4a99-aa22-85743224560f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit_longitude</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'edit_longitude']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#edit_longitude</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d107299d-55df-4f9c-a6bd-41be09637b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>05ca3d68-fffa-4568-9728-33d1b0cb59e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>longitude</value>
      <webElementGuid>724e9bda-1a97-4983-91b8-2203da6d2927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit_longitude</value>
      <webElementGuid>a8c8b867-b5af-436a-9104-14d1177d8e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-model</name>
      <type>Main</type>
      <value>editingDest.longitude</value>
      <webElementGuid>a7923a28-d4b4-40b6-8300-e8c1dfa72ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full border border-gray-200 rounded-xl px-4 py-3.5 focus:ring-2 focus:ring-sidebar/10 focus:border-sidebar outline-none text-sm font-medium text-gray-700</value>
      <webElementGuid>914c980e-f555-439c-b70a-573749a0a6dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f89746d666e329fbc404fde6643d986c</value>
      <webElementGuid>8560b6d9-4151-499a-9129-93209f12420b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'edit_longitude']</value>
      <webElementGuid>5b882358-9145-47cd-a76b-fc0827c9e7cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'edit_longitude']</value>
      <webElementGuid>c5d20571-354d-4fea-b906-fd2dba4a0ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'longitude' and @id = 'edit_longitude']</value>
      <webElementGuid>50444646-30c6-4afe-940c-7293d4d9c254</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
