<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_description</name>
   <tag></tag>
   <elementGuidId>313ccd5a-9897-496b-ba5d-780f4e555fe7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[x-model=&quot;editingDest\.description&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@x-model = 'editingDest.description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#editDestForm textarea[name=&quot;description&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a97b5c17-6e5d-469f-af8d-91e95e4d1843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>83ada380-f922-404b-a129-a6f76dd98fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>5d76aa20-392a-41ca-80f2-3d2c95186de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-model</name>
      <type>Main</type>
      <value>editingDest.description</value>
      <webElementGuid>eacb9d83-4680-4330-a43d-f52b511c0f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full border border-gray-200 rounded-xl px-4 py-3.5 focus:ring-2 focus:ring-sidebar/10 focus:border-sidebar outline-none text-sm font-medium text-gray-700</value>
      <webElementGuid>655b254b-ab54-45f4-9c9c-a8dea2c82f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-add13e27848cbaea9eaf053d8e47e839</value>
      <webElementGuid>bff76f06-c03c-4020-bf85-6e7cd294bcb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@x-model = 'editingDest.description']</value>
      <webElementGuid>12aec22a-3a6f-4a78-b518-28c58cb990ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@x-model = 'editingDest.description']</value>
      <webElementGuid>438d023e-9c99-497f-a8b5-49362a08320a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'description']</value>
      <webElementGuid>2715e5ec-5acf-4a6b-b17b-22bd07250aea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
