analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3461592,"name"\:"Sample - HR Web App \#3461592","teamId"\:3443596,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3486819,"accountId"\:null,"sampleProject"\:false,"autoIntegrate"\:false}
analytics.team={"id"\:3443596,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
